# Generated by Django 5.0.3 on 2024-03-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_spotifyuserinfo_delete_spotifydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuserinfo',
            name='tracks_data',
            field=models.JSONField(default=list),
        ),
    ]
